isr_exception_stub_0:
    cli
    hlt
    jmp isr_exception_stub_0

isr_exception_stub_1:
    cli
    hlt
    jmp isr_exception_stub_1

isr_exception_stub_2:
    cli
    hlt
    jmp isr_exception_stub_2

isr_exception_stub_3:
    cli
    hlt
    jmp isr_exception_stub_3

isr_exception_stub_4:
    cli
    hlt
    jmp isr_exception_stub_4

isr_exception_stub_5:
    cli
    hlt
    jmp isr_exception_stub_5

isr_exception_stub_6:
    cli
    hlt
    jmp isr_exception_stub_6

isr_exception_stub_7:
    cli
    hlt
    jmp isr_exception_stub_7

isr_exception_stub_8:
    cli
    hlt
    jmp isr_exception_stub_8

isr_exception_stub_9:
    cli
    hlt
    jmp isr_exception_stub_9

isr_exception_stub_10:
    cli
    hlt
    jmp isr_exception_stub_10

isr_exception_stub_11:
    cli
    hlt
    jmp isr_exception_stub_11

isr_exception_stub_12:
    cli
    hlt
    jmp isr_exception_stub_12

isr_exception_stub_13:
    cli
    hlt
    jmp isr_exception_stub_13

isr_exception_stub_14:
    cli
    hlt
    jmp isr_exception_stub_14

isr_exception_stub_15:
    cli
    hlt
    jmp isr_exception_stub_15

isr_exception_stub_16:
    cli
    hlt
    jmp isr_exception_stub_16

isr_exception_stub_17:
    cli
    hlt
    jmp isr_exception_stub_17

isr_exception_stub_18:
    cli
    hlt
    jmp isr_exception_stub_18

isr_exception_stub_19:
    cli
    hlt
    jmp isr_exception_stub_19

isr_exception_stub_20:
    cli
    hlt
    jmp isr_exception_stub_20

isr_exception_stub_21:
    cli
    hlt
    jmp isr_exception_stub_21

isr_exception_stub_22:
    cli
    hlt
    jmp isr_exception_stub_22

isr_exception_stub_23:
    cli
    hlt
    jmp isr_exception_stub_23

isr_exception_stub_24:
    cli
    hlt
    jmp isr_exception_stub_24

isr_exception_stub_25:
    cli
    hlt
    jmp isr_exception_stub_25

isr_exception_stub_26:
    cli
    hlt
    jmp isr_exception_stub_26

isr_exception_stub_27:
    cli
    hlt
    jmp isr_exception_stub_27

isr_exception_stub_28:
    cli
    hlt
    jmp isr_exception_stub_28

isr_exception_stub_29:
    cli
    hlt
    jmp isr_exception_stub_29

isr_exception_stub_30:
    cli
    hlt
    jmp isr_exception_stub_30

isr_exception_stub_31:
    cli
    hlt
    jmp isr_exception_stub_31

.global isr_exception_stub_table
isr_exception_stub_table:
    .4byte isr_exception_stub_0
    .4byte isr_exception_stub_1
    .4byte isr_exception_stub_2
    .4byte isr_exception_stub_3
    .4byte isr_exception_stub_4
    .4byte isr_exception_stub_5
    .4byte isr_exception_stub_6
    .4byte isr_exception_stub_7
    .4byte isr_exception_stub_8
    .4byte isr_exception_stub_9
    .4byte isr_exception_stub_10
    .4byte isr_exception_stub_11
    .4byte isr_exception_stub_12
    .4byte isr_exception_stub_13
    .4byte isr_exception_stub_14
    .4byte isr_exception_stub_15
    .4byte isr_exception_stub_16
    .4byte isr_exception_stub_17
    .4byte isr_exception_stub_18
    .4byte isr_exception_stub_19
    .4byte isr_exception_stub_20
    .4byte isr_exception_stub_21
    .4byte isr_exception_stub_22
    .4byte isr_exception_stub_23
    .4byte isr_exception_stub_24
    .4byte isr_exception_stub_25
    .4byte isr_exception_stub_26
    .4byte isr_exception_stub_27
    .4byte isr_exception_stub_28
    .4byte isr_exception_stub_29
    .4byte isr_exception_stub_30
    .4byte isr_exception_stub_31

