#pragma once

#define PS2_DATA_PORT 0x60
#define PS2_STATUS_REGISTER 0x64
#define PS2_COMMAND_REGISTER 0x64

#define STATUS_OUTPUT       0x01
#define STATUS_INPUT        0x02
#define STATUS_SYSTEM       0x04
#define STATUS_COMMAND_TYPE 0x08
#define STATUS_TIMEOUT      0x40
#define STATUS_PARITY       0x80

/* COMMANDS */

#define CMD_DISABLE_PORT1   0xA7
#define CMD_DISABLE_PORT2   0xAD
#define CMD_ENABLE_PORT1    0xA8
#define CMD_ENABLE_PORT2    0xAE

#define CMD_READ_CTRL_CONF  0x20
#define CMD_WRITE_CTRL_CONF 0x60

#define CMD_READ_CTRL_OUTPUT_PORT    0xD0
#define CMD_WRITE_CTRL_OUTPUT_PORT   0xD1

#define CMD_CTRL_SELF_TEST  0xAA
#define CMD_PORT1_SELF_TEST 0xAB
#define CMD_PORT2_SELF_TEST 0xA9

/* Bit stuff */

#define CTRL_CONF_PORT1_INT     0x01
#define CTRL_CONF_PORT2_INT     0x02
#define CTRL_CONF_SYSTEM        0x04
#define CTRL_CONF_PORT1_CLOCK   0x10
#define CTRL_CONF_PORT2_CLOCK   0x20
#define CTRL_CONF_PORT1_TRANS   0x40

#define CTRL_OUTPUT_PORT_SYS_RST        0x01
#define CTRL_OUTPUT_PORT_A20            0x02
#define CTRL_OUTPUT_PORT_PORT2_CLK      0x04
#define CTRL_OUTPUT_PORT_PORT2_DATA     0x08
#define CTRL_OUTPUT_PORT_PORT1_ON_DATA  0x10
#define CTRL_OUTPUT_PORT_PORT2_ON_DATA  0x20
#define CTRL_OUTPUT_PORT_PORT1_CLK      0x40
#define CTRL_OUTPUT_PORT_PORT1_DATA     0x80

